kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: jenkins
